### PR TITLE
docs: fix typos and wording issues in menu docs

### PR DESCRIPTION
**Pull request by kspar**

### CODE REVIEW

**Review by asyncLiz — CHANGES_REQUESTED** [review]
These docs are autogenerated from jsdoc in code. Could you update these instances in [the menu's typescript code jsdoc](https://github.com/material-components/material-web/blob/6b95a13ee1fd4203140aeda89c24c7afb8acdde1/menu/internal/menu.ts#L101) as well?

**Review by asyncLiz — APPROVED** [review]

**Comment by asyncLiz** [comment]
Can you take a look at the [cla bot](https://github.com/material-components/material-web/pull/5455/checks?check_run_id=214923473480)?

**Comment by kspar** [comment]
I'm not sure what you mean, I see that it's all green

**Comment by asyncLiz** [comment]
Ah nvm, I see it now!

**Pull request merged**
