### PR TITLE
build: update dependencies

### PR DESCRIPTION
**Pull request by e111077**
lit ssr update includes a fix for defer-hydration

https://github.com/lit/lit/issues/3939

### CODE REVIEW

**Review by asyncLiz — APPROVED** [review]
lgtm

**Comment by AxelBriche** [comment]
> lit ssr update includes a fix for defer-hydration
> 
> [lit/lit#3939](https://github.com/lit/lit/issues/3939)

material-web is ssr compatible?

**Comment by e111077** [comment]
material-web 1.0 has a best-effort but not yet official support for SSR. They currently all _work_ in SSR but require more extensive testing.

Though, this means that it is SSRable with the lit-ssr library. Those frameworks need to know to call the lit-ssr library. For NextJS there is an official Lit plugin:

https://www.npmjs.com/package/@lit-labs/nextjs

For Nuxt we have worked with some community members to enable this integration:

https://github.com/prashantpalikhe/nuxt-ssr-lit

[Astro](https://astro.build) already supports Lit SSR out of the box

There is an official plugin for Eleventy + Lit SSR:

https://www.npmjs.com/package/@lit-labs/eleventy-plugin-lit

We currently do not know anything about Svelte and SSR integrations, but if you are interested in contributing, I recommend joining the [Lit discord](https://lit.dev/discord) and expressing interest in the #get-involved channel

**Comment by Aworldc** [comment]
I'm in the process of building a svelte wrapper, so I'll definitely look in to integrating this.

**Comment by e111077** [comment]
@Aworldc Highly recommend chiming in on the #get-involved channel on the lit discord if you don't know where or how to get started integrating it. That channel is there to help contributors. team members there would be super happy to point you in the right direction and answer questions about requirements to get lit-ssr running / integrated etc.

**Pull request merged**
