### PR TITLE
docs: add textfield docs

### PR DESCRIPTION
**Pull request by stiblook**
- Added textfield docs, without catalog rendering, and,
- Added Filled Button example image in docs rendered on github.

### CODE REVIEW

**Comment by stiblook** [comment]
Fixed the title now..

**Comment by stiblook** [comment]
updated the title...

**Review by asyncLiz — CHANGES_REQUESTED** [review]
Hi! Thank you so much for this contribution! This will be a good starting point for our text field docs.

These docs are imported internally, and unfortunately we have some pretty stringent guidelines and internal tool updating that we have to do before displaying it. I feel like that might cause a lot of back-and-forth churn while reviewing this.

Instead, can you create a subfolder, `docs/contrib/` and move the files and images into that folder? That way we can import it faster and move it into the main docs folder after it's ready internally.

**Comment by Aamir333** [comment]
Thank you

**Comment by asyncLiz** [comment]
Thank you! Might not get to reviewing this until next week though with the US holiday coming up

**Comment by asyncLiz** [comment]
Thank you so much for your PR, we appreciate it! Closing though since we're publishing text field docs in #4709

**Pull request closed without merging**
