### PR TITLE
Add ARIA presentation role to ripple

### PR DESCRIPTION
**Pull request by steverep**

### CODE REVIEW

**Comment by asyncLiz** [comment]
What is this PR solving for? The ripple should not be read by screen readers.

**Comment by steverep** [comment]
> What is this PR solving for? The ripple should not be read by screen readers.

Explained in issue #2986 - just because there is no text for assistive technology to consume doesn't mean it's invisible.  The ARIA none role is exactly for stuff like this.

**Comment by asyncLiz** [comment]
Thanks for the issue link. Can you describe what the behavior of screen readers are when there is not a role attribute on the ripple?

**Comment by steverep** [comment]
> Thanks for the issue link. Can you describe what the behavior of screen readers are when there is not a role attribute on the ripple?

It depends both on the screen reader and browser.  First, users can always navigate the accessibility tree manually when needed (e.g. NVDA calls this object navigation).  The `<div>` just appears as an empty text container or similar (non-semantic elements like `div` or `span` can be in the tree differently depending on the accessibility API).  Adding `role="none"` tells the user agent to ignore the generic role, and since it's empty it effectively removes it from the tree so it won't be navigated in that mode.

Second, user agents are supposed to treat all children of things such as buttons as presentation/none, but that doesn't always happen, especially when shadow boundaries are involved.  When they aren't, it can cause confusion when browsed because the boundaries of such elements are not announced and semantics inside them are not conventional/expected.

Adding the role as I show here is the right thing to do.  I would encourage you to read about these topics in the W3C ARIA 1.2 spec and related documents for greater detail.

**Comment by steverep** [comment]
I'm willing to fix other accessibility issues, but is this project not reviewing outside pull requests?  This is not a particularly taxing review at 1 changed line.

**Comment by asyncLiz** [comment]
At the moment 100% of our energy is focused towards Material You, which is why only critical PRs are currently being reviewed.

We've gone through our internal a11y review and have determined that it is not necessary to add this role. If a screenreader is announcing arbitrary `<div>`s, I'd recommend creating a small repro and filing a bug on that screenreader!

**Comment by steverep** [comment]
> We've gone through our internal a11y review and have determined that it is not necessary to add this role. If a screenreader is announcing arbitrary <div>s, I'd recommend creating a small repro and filing a bug on that screenreader!

There's no screen reader problem here, and nothing I've commented has suggested that the issue was with arbitrary announcements.

I've acknowledged on the issue thread that the behavior has changed since I first filed it, but I've also commented in detail and pointed to W3C references as to why this ought to be removed from the accessibility tree.  The latter has largely gone without response.

**Pull request closed without merging**
