### PR TITLE
chore: rewriting property attributes to kebab-case

### PR DESCRIPTION
**Pull request by vdegenne**
@asyncLiz Just like that?

### CODE REVIEW

**Comment by asyncLiz** [comment]
Yes! Though before we continue with it, we'll probably want to chat about it in our eng meeting next Thursday and confirm if we want to do it and what the scope it

**Comment by vdegenne** [comment]
Ok nice, I will wait, if needed I can do it, always glad to help you!

**Comment by AndrewJakubowicz** [comment]
Sorry - I missed this PR! I think all compound attributes should now be kebab-case.

**Comment by vdegenne** [comment]
@AndrewJakubowicz It's ok :) I saw the changes you've made.

> I think all compound attributes should now be kebab-case.

You mean you've modified all the files? If there are any files left, I can continue the charge if you want.

**Comment by vdegenne** [comment]
@AndrewJakubowicz Closing as obsolete.

**Pull request closed without merging**
