### PR TITLE
fix(linearprogress): rename fourColors to fourColor

### PR DESCRIPTION
**Pull request by bre97-web**
#4237

### CODE REVIEW

**Review by asyncLiz — APPROVED** [review]
Thanks for this fix! Just need CLA :)

**Comment by bre97-web** [comment]
Maybe need to go through commitlint?

**Comment by asyncLiz** [comment]
> Maybe need to go through commitlint?

You need to sign [the CLA from the bot above](https://github.com/material-components/material-web/pull/4241#issuecomment-1535662048).

**Comment by asyncLiz** [comment]
Oh this is my bad, I didn't see the CLA get signed. Importing now!

**Pull request merged**
