### PR TITLE
docs: fix repo links replace material-components-web with material-web

### PR DESCRIPTION
**Pull request by schirrel**
Related to PR #3260 and issue #3252

### CODE REVIEW

**Comment by schirrel** [comment]
@asyncLiz if you had a time i'd be glad if you could take a look

**Comment by asyncLiz** [comment]
> @asyncLiz if you had a time i'd be glad if you could take a look

Unfortunately I am swamped right now and don't have cycles to review this 😔

This will also be rendered obsolete very shortly once we get the repo updating again, which is why I'm leaning towards holding off on it.

**Comment by MrBirb** [comment]
@asyncLiz There hasn’t been any update in a long time. Is everything ok?

**Comment by asyncLiz** [comment]
Thanks for this contribution, but with the current state of the repository we're going to close this for now :)

**Pull request closed without merging**
